Fix install process
bcgalvin/metaflow pull request #1
Opened 2020-09-13 04:29 UTC by jasonge27

1. activate conda/virtualenv before check_python_dependencies()
2. set required=TRUE for use_conda and use_virtualenv, to enforce the correct environment.
3. use reticulate functions via reticulate::function_name() to improve readability
4. In install_metaflow(), if conda binary is not detected, we add a user prompt and ask permission to install Miniconda on user's behalf.

2020-09-13 10:25 UTC, bcgalvin commented on R/R/zzz.R
> +  activate_metaflow_env()
I think having `activate_metaflow_env()` in `.onLoad` is sufficient, having it in both places means it's run twice and `onLoad` covers the case when the package is referenced via `metaflow::` and `library(metaflow)` whereas `onAttach` only fires with `library(metaflow)`

2020-09-13 10:27 UTC, bcgalvin commented on R/R/install.R
> +activate_metaflow_env <- function(envname = "metaflow-r") {
dig the new function name

2020-09-13 10:30 UTC, bcgalvin commented on R/R/install.R
> +    reticulate::py_module_available("numpy"),
think being explicit is the way to go as well, we should be consistent with using `::` so can remove reticulate from the `imports.R` file and use the `::` notation for the R6 dependencies that are declared (need to leave magrittr alone for the pipes to work though)

2020-09-13 10:32 UTC, bcgalvin commented on R/R/zzz.R
> +
can/should setting`METAFLOW_PYTHON` be moved to `activate_metaflow_env`?

2020-09-13 10:46 UTC, bcgalvin commented on R/R/zzz.R
> +  activate_metaflow_env()
I think it makes sense to move the environment checking functions that are in `install.R` to `zzz.R` to be closer to where they get called (and they aren't really related to the actual install in any way)

2020-09-13 10:47 UTC, bcgalvin requested changes
Added a few comments but looks good. The only business logic change that may be needed is to avoid activating the miniconda prompt with `onLoad`/`onAttach`, currently on a minimal ubuntu image we get:

> `>` library(metaflow)
`>` No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

and other R packages for python libs don't have that going on:
> `>` library(mlflow)
`>` library(tensorflow)
`>` 

This would be non-trivial to do since I think it would mean changing how metaflow python gets loaded (so `metaflow_load()`). It's slightly annoying but not sure if it's worth delaying this PR.

2020-09-14 07:00 UTC, bcgalvin commented on R/R/zzz.R
> +pkg.env$envname = "metaflow-r"
nit but maybe should change the default envname to `r-metaflow`, default environment for reticulate is `r-reticulate` and other R packages that wrap python libraries follow this convention:
- https://rstudio.github.io/reticulate/articles/python_packages.html
- https://github.com/mlflow/mlflow/blob/master/mlflow/R/mlflow/R/install.R#L8

2020-09-14 07:21 UTC, bcgalvin commented
the conda install follows the happy path now but virtualenv has some weird behavior still:

```
Successfully installed astroid-2.3.3 boto3-1.14.60 botocore-1.17.60 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 docutils-0.15.2 isort-4.3.21 jmespath-0.10.0 lazy-object-proxy-1.4.3 mccabe-0.6.1 metaflow-2.2.3 numpy-1.19.2 pandas-1.1.2 pylint-2.4.4 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 s3transfer-0.3.3 typed-ast-1.4.1 urllib3-1.25.10 wrapt-1.11.2
> test()
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
Installation aborted.
  
Metaflow 2.2.0 executing HelloWorldFlow for user:rstudio
Validating your flow...
    The graph looks good!

2020-09-14 07:08:24.732 Workflow starting (run-id 1600067304619266):
2020-09-14 07:08:24.787 [1600067304619266/start/1 (pid 177)] Task is starting.
2020-09-14 07:08:27.167 [1600067304619266/start/1 (pid 177)] [1] "Your Metaflow installation looks good!"
2020-09-14 07:08:27.441 [1600067304619266/start/1 (pid 177)] Task finished successfully.
2020-09-14 07:08:27.507 [1600067304619266/end/2 (pid 219)] Task is starting.
2020-09-14 07:08:30.081 [1600067304619266/end/2 (pid 219)] Task finished successfully.
2020-09-14 07:08:30.101 Done!
```
It successfully installs metaflow using virtualenv based on the system python but still prompts for miniconda if run immediately after `install_metaflow()`, this behavior doesn't happen if R is reloaded however.

@jasonge27

2020-09-14 19:21 UTC, jasonge27 commented on R/R/zzz.R
> +  activate_metaflow_env()
Good point. My understanding is that .onAttach is always called automatically before .onLoad -- is this correct? If so we can remove the `activate_metaflow_env` in .onLoad?

2020-09-14 19:23 UTC, jasonge27 commented on R/R/install.R
> +    reticulate::py_module_available("numpy"),
We do have `R6::R6Class` whenever we use `R6Class`.I'll remove the `importFrom(R6,R6Class)` from NAMESPACE

2020-09-14 19:24 UTC, jasonge27 commented on R/R/zzz.R
> +
that's a good point! Moving it now.

2020-09-14 19:24 UTC, jasonge27 commented on R/R/zzz.R
> +  activate_metaflow_env()
Agree. Moving them.

2020-09-14 19:25 UTC, jasonge27 commented on R/R/zzz.R
> +pkg.env$envname = "metaflow-r"
Good point! Making the change

2020-09-14 19:48 UTC, jasonge27 commented on R/R/zzz.R
> +  activate_metaflow_env()
I'm merging onAttach with onLoad, and only keep onLoad, since  (1) it's only printing the R/Py versions in onAttach (2) it's rare to only call onAttach without onLoad (3) other projects such as spacy only has onLoad as well https://github.com/quanteda/spacyr/blob/master/R/zzz.R

2020-09-15 00:24 UTC, bcgalvin commented on R/R/install.R
> +    reticulate::py_module_available("numpy"),
Can remove it from imports.R as well and it’ll handle the NAMESPACE entry next time you build docs. Since we’re using :: everywhere only need the magrittr pipe in there.

2020-09-15 03:40 UTC, jasonge27 commented on R/R/install.R
> +    reticulate::py_module_available("numpy"),
Yes it was removed from imports.R as well!

2020-09-15 07:19 UTC, bcgalvin commented
Really like the ergonomics around the python dependencies w this PR. I ran into one corner case with multiple installations, here's a reproducible example:

```
library(metaflow)
install_metaflow(method='virtualenv')
install_metaflow(method='conda')
```

```
...
Downloading and Extracting Packages
python-3.8.5         | 21.9 MB   | ######################################################## | 100% 
setuptools-49.6.0    | 951 KB    | ######################################################## | 100% 
python_abi-3.8       | 4 KB      | ######################################################## | 100% 
certifi-2020.6.20    | 151 KB    | ######################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate r-metaflow
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Using virtual environment 'r-metaflow' ...
Requirement already up-to-date: metaflow in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (2.2.3)
Requirement already up-to-date: numpy in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (1.19.2)
Requirement already up-to-date: pandas in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (1.1.2)
Requirement already satisfied, skipping upgrade: pylint<2.5.0 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from metaflow) (2.4.4)
Requirement already satisfied, skipping upgrade: click>=7.0 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from metaflow) (7.1.2)
Requirement already satisfied, skipping upgrade: boto3 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from metaflow) (1.14.61)
Requirement already satisfied, skipping upgrade: requests in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from metaflow) (2.24.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from pandas) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from pandas) (2020.1)
Requirement already satisfied, skipping upgrade: isort<5,>=4.2.5 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from pylint<2.5.0->metaflow) (4.3.21)
Requirement already satisfied, skipping upgrade: astroid<2.4,>=2.3.0 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from pylint<2.5.0->metaflow) (2.3.3)
Requirement already satisfied, skipping upgrade: mccabe<0.7,>=0.6 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from pylint<2.5.0->metaflow) (0.6.1)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from boto3->metaflow) (0.10.0)
Requirement already satisfied, skipping upgrade: s3transfer<0.4.0,>=0.3.0 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from boto3->metaflow) (0.3.3)
Requirement already satisfied, skipping upgrade: botocore<1.18.0,>=1.17.61 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from boto3->metaflow) (1.17.61)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->metaflow) (2.6)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from requests->metaflow) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from requests->metaflow) (2020.6.20)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from requests->metaflow) (1.25.10)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7.3->pandas) (1.11.0)
Requirement already satisfied, skipping upgrade: typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from astroid<2.4,>=2.3.0->pylint<2.5.0->metaflow) (1.4.1)
Requirement already satisfied, skipping upgrade: lazy-object-proxy==1.4.* in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from astroid<2.4,>=2.3.0->pylint<2.5.0->metaflow) (1.4.3)
Requirement already satisfied, skipping upgrade: wrapt==1.11.* in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from astroid<2.4,>=2.3.0->pylint<2.5.0->metaflow) (1.11.2)
Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in /root/.virtualenvs/r-metaflow/lib/python3.6/site-packages (from botocore<1.18.0,>=1.17.61->boto3->metaflow) (0.15.2)
ERROR: The requested version of Python
('/root/.local/share/r-miniconda/envs/r-metaflow/bin/python') cannot be
used, as another version of Python
('/root/.virtualenvs/r-metaflow/bin/python') has already been
initialized. Please restart the R session if you need to attach
reticulate to a different version of Python.
Error in use_python(python, required = required) : 
  failed to initialize requested version of Python
```
The conda install will fail if there's an existing virtualenv install (also occurs if trying to install via conda in a fresh R session when a virtualenv install already exists). 

While this probably won't come up too often I think we could check for an existing install and then if detected prompt the user to handle this condition:


```
# existing virtualenv w metaflow python detected and conda selected
1. continue with conda installation (virtualenv will be removed)
2. install using virtualenv instead
```

2020-09-18 13:09 UTC, bcgalvin commented
business logic of detecting the existing install works but it prompts the user twice when calling `remove_metaflow()`:
```
> remove_metaflow(method='virtualenv')
A virtualenv environment r-metaflow will be removed

Proceed? 

1: No
2: Yes

Selection: 2
Remove virtual environment 'r-metaflow'? [Y/n]: y
Virtual environment 'r-metaflow' removed.
```
added arg to `reticulate::virtualenv_remove()` to bypass the extra prompt


Last question for you @jasonge27 before it gets the LGTM from me: 
- in `remove_metaflow`, we should be able to detect the existing environment via `check_environment()` so the method argument isn't really necessary is it?

2020-09-24 16:56 UTC, merged